.TH WDMD 8 2011-08-01

.SH NAME
wdmd \- watchdog multiplexing daemon

.SH SYNOPSIS
.B wdmd
[OPTIONS]

.SH DESCRIPTION

This daemon opens /dev/watchdog and allows multiple independent sources to
detmermine whether each KEEPALIVE is done.  Every test interval (10
seconds), the daemon tests each source.  If any test fails, the KEEPALIVE
is not done.  In a standard configuration, the watchdog timer will reset
the system if no KEEPALIVE is done for 60 seconds ("fire timeout").  This
means that if single test fails 5-6 times in row, the watchdog will fire
and reset the system.  With multiple test sources, fewer separate failures
back to back can also cause a reset, e.g.

T seconds, P pass, F fail
.br
T00: test1 P, test2 P, test3 P: KEEPALIVE done
.br
T10: test1 F, test2 F, test3 P: KEEPALIVE skipped
.br
T20: test1 F, test2 P, test3 P: KEEPALIVE skipped
.br
T30: test1 P, test2 F, test3 P: KEEPALIVE skipped
.br
T40: test1 P, test2 P, test3 F: KEEPALIVE skipped
.br
T50: test1 F, test2 F, test3 P: KEEPALIVE skipped
.br
T60: test1 P, test2 F, test3 P: KEEPALIVE skipped
.br
T60: watchdog fires, system resets

(Depending on timings, the system may be reset sometime shortly before
T60, and the tests at T60 would not be run.)

A crucial aspect to the design and function of wdmd is that if any single
source does not pass tests for the fire timeout, the watchdog is
guaranteed to fire, regardless of whether other sources on the system have
passed or failed.  A spurious reset due to the combined effects of
multiple failing tests as shown above, is an accepted side effect.

wdmd will exit if a watchdog driver is not loaded.

wdmd cannot be used on the system with any other program that needs to
open /dev/watchdog, e.g. watchdog(8).

.SS Test Source: clients

Using libwdmd, programs connect to wdmd via a unix socket, and send
regular messages to wdmd to update an expiry time for their connection.
Every test interval, wdmd will check if the expiry time for a connection
has been reached.  If so, the test for that client fails.

(Other test sources such as scripts executed each test interval may be
added in the future.)

.SH OPTIONS
.TP
.B \-D
Enable debugging to stderr and don't fork.

.TP
.BI \-H " num"
Enable (1) or disable (0) high priority features such as realtime
scheduling priority and mlockall.
.br
Default 1.

