#!/bin/sh
#
# wdmd - watchdog multiplexing daemon
#
# chkconfig: 2345 97 03
# description: starts and stops sanlock daemon
#


### BEGIN INIT INFO
# Provides: wdmd
# Required-Start: $time $syslog
# Required-Stop: $syslog
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: starts and stops wdmd daemon
# Description: starts and stops wdmd daemon
### END INIT INFO

. /etc/rc.d/init.d/functions

prog="wdmd"
lockfile="/var/run/$prog/$prog.pid"
exec="/usr/sbin/$prog"

WDMDGROUP="sanlock"
WDMDOPTS="-G $WDMDGROUP"

[ -f /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

start() {
	[ -x $exec ] || exit 5

	if [ ! -d /var/run/$prog ]; then
		mkdir -p /var/run/$prog
		[ -x /sbin/restorecon ] && restorecon /var/run/$prog
	fi

	echo -n $"Starting $prog: "
	daemon $prog $WDMDOPTS
	retval=$?
	echo
	[ $retval -eq 0 ] && touch $lockfile
	return $retval
}

stop() {
	echo -n $"Stopping $prog: "
	killproc -p $lockfile $prog -TERM
	retval=$?
	echo
	[ $retval -eq 0 ] && rm -f $lockfile
}

restart() {
	stop
	start
}

reload() {
	restart
}

rh_status() {
	status $prog
}

rh_status_q() {
	rh_status >/dev/null 2>&1
}

case "$1" in
	start)
		rh_status_q && exit 0
		$1
		;;
	stop)
		rh_status_q || exit 0
		$1
		;;
	restart)
		$1
		;;
	reload)
		rh_status_q || exit 7
		$1
		;;
	force-reload)
		force_reload
		;;
	status)
		rh_status
		;;
	condrestart|try-restart)
		rh_status_q || exit 0
		restart
		;;
	*)
		echo $"Usage $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
		exit 2
esac
exit $?

