# Copyright (C) 2022 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python_version: '3.6'
          - python_version: '3.7'
          - python_version: '3.8'
          - python_version: '3.9'
          - python_version: '3.10'
          - python_version: '3.11'
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python_version}}
          cache: 'pip'
          check-latest: true

      - name: Install required packages
        run: sudo apt install -y gcc make libaio-dev libblkid-dev uuid-dev

      - name: Install pip requirements
        run: pip install -r requirements.txt

      - name: Setup userstorage
        run: userstorage create tests/storage.py

      - name: Run tests
        run: tox
